name: Localize

on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          xcodebuild clean -project ActionsPlayground.xcodeproj -scheme ActionsPlayground -target ActionsPlayground  -sdk iphonesimulator -configuration Debug build
          bash <(curl -s https://codecov.io/bash)
