name: CheckLocalize

on:
  push:
    paths:
      - 'ActionsPlayground/Localizable/**'

jobs:
  build:
    name: Run Localizer
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Localize
        run: |
          echo "処理開始"
          ActionsPlayground/Localizable/Localizer
          result=$?
          if [ $result -eq 0] ; then
            echo "ok"
          else
            echo "ng"
          fi
          echo "終了"

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()  # jobの成否に関わらずSlackへ通知
        with:
          type: ${{ job.status }}  # jobの成否を代入(Failure/Success)
          job_name: '*Lint Check*'
          channel: '#random'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
