name: CheckLocalize

on: push
#  push:
#    paths:
#      - 'ActionsPlayground/Localizable/**'

jobs:
  build:
    name: Run Localizer
    runs-on: macos-latest
    env:
      MYVAL: ''

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Localize
        run: |
          echo "処理開始"
          MYVAL=ActionsPlayground/Localizable/Localizer
          result=$?
          if [ $result -eq 0] ; then
            echo "ok"
          else
            echo "ng"
            echo $MYVAL
            exit 1
          fi
          echo "終了"

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}  # jobの成否を代入(Failure/Success)
          job_name: '${MYVAL}'
          username: 'Localizer'
          channel: '#random'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
