name: CheckLocalize

on:
  push:
    paths:
      - 'ActionsPlayground/Localizable/**'

jobs:
  build:
    name: Run Localizer
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Localize
        run: |
          echo "処理開始"
          result=`ActionsPlayground/Localizable/Localizer 2>/dev/null || true`
          if test $result = "★正常終了" ; then
            echo "ok"
            echo $result
          else
            echo "ng"
            echo $result 1>&2
          fi
          echo "終了"
